name               = "s19-dev-ops-main-site"
account_id         = "e009cc59dc575aa603d8084da155c32e"
workers_dev        = true
compatibility_date = "2025-07-30"
compatibility_flags = ["nodejs_compat"]

# Point to Astro’s Worker bundle
main               = "dist/_worker.js"

[site]
# Serve everything in dist/ as static assets
bucket             = "./dist"
