// ⚠️ AUTO-GENERATED by scripts/gen-env-types.mjs — do not edit by hand.
// Run: npm run gen:envtypes
// This file is generated from your wrangler.toml bindings.

/// <reference types="@cloudflare/workers-types" />

// Extra CF types (Vectorize/Hyperdrive/Ai) may not exist in older workers-types versions.
// Fallback shims so TS doesn't error if your package doesn't include them.
type VectorizeIndex = any;
type Hyperdrive = any;
type Ai = any;

type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

// Generated from wrangler.toml
interface Env {
  // (no bindings declared in wrangler.toml)

}

declare namespace App {
  interface Locals extends Runtime {}
}
