// ⚠️ AUTO-GENERATED by scripts/gen-env-types.mjs — do not edit by hand.
// Run: npm run gen:envtypes
// This file is generated from your wrangler.toml bindings.

/// <reference types="@cloudflare/workers-types" />

// Extra CF types may not exist in older workers-types versions.
// We only add shims for ones not present (see skipTypes).


type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

// Generated from wrangler.toml
interface Env {
  // (no bindings declared in wrangler.toml)

}

declare namespace App {
  interface Locals extends Runtime {}
}
